define("js/wx_share",["jquery","http://res.wx.qq.com/open/js/jweixin-1.0.0.js"],function(a){
    "user strict";var $=a("jquery");var wx=a('http://res.wx.qq.com/open/js/jweixin-1.0.0.js');
$.ajax({
  type:"GET",
  url:"http://wx.5usport.com/Jsapisign",
  data:{signurl:e},
  dataType:"json",
  success:function(e){
    //alert(e.appid);
    wx.config({
      debug:!1,
      appId:e.appid,
      timestamp:e.timestamp,
      nonceStr:e.noncestr,
      signature:e.signature,
      jsApiList:["checkJsApi","onMenuShareTimeline","onMenuShareAppMessage"]
      })
    },
  error:function(){
    showmsg('数据有误','',1000)
  }
})

wx.ready(function(){
  wx.showOptionMenu(),
  wx.onMenuShareAppMessage({
    title:shareTitle,
    desc:shareDescription,
    link:shareUrl,
    imgUrl:shareImage,
    trigger:function(e){},
    success:function(e){
      sharesucess();
    },
    cancel:function(e){},
    fail:function(e){}
  })
  wx.onMenuShareTimeline({
    title:shareTitle,
    link:shareUrl,
    imgUrl:shareImage,
    trigger:function(e){},
    success:function(e){
      sharesucess();
    },
    cancel:function(e){},
    fail:function(e){}
  })
})
wx.error(function(e){
  alert(e.errMsg)
});

});